CREATE TABLE [dbo].[CATEGORIA]
(
[IDCAT] [int] NOT NULL IDENTITY(1, 1),
[NOMCAT] [varchar] (150) COLLATE Modern_Spanish_CI_AS NULL,
[DESCAT] [varchar] (255) COLLATE Modern_Spanish_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CATEGORIA] ADD CONSTRAINT [PK__CATEGORI__91A9FC3CC57784E1] PRIMARY KEY CLUSTERED  ([IDCAT]) ON [PRIMARY]
GO
