CREATE TABLE [dbo].[DETALLE_BOLETA]
(
[IDDETABOL] [int] NOT NULL IDENTITY(1, 1),
[IDPRO] [int] NULL,
[CANTIDAD] [int] NULL,
[PERCIO] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DETALLE_BOLETA] ADD CONSTRAINT [PK__DETALLE___BE33F299BC93B395] PRIMARY KEY CLUSTERED  ([IDDETABOL]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DETALLE_BOLETA] ADD CONSTRAINT [PRODUCTO_DETALLE_BOLETA_IDPRO] FOREIGN KEY ([IDPRO]) REFERENCES [dbo].[PRODUCTOS] ([IDPRO])
GO
