CREATE TABLE [dbo].[BOLETA]
(
[IDBOL] [int] NOT NULL IDENTITY(1, 1),
[IDPER] [int] NULL,
[FECHBOL] [date] NULL,
[IDDETABOL] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BOLETA] ADD CONSTRAINT [PK__BOLETA__936695B76D79A213] PRIMARY KEY CLUSTERED  ([IDBOL]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BOLETA] ADD CONSTRAINT [DETALLE_BOLETA_IDDETBOL] FOREIGN KEY ([IDDETABOL]) REFERENCES [dbo].[DETALLE_BOLETA] ([IDDETABOL])
GO
ALTER TABLE [dbo].[BOLETA] ADD CONSTRAINT [PERSONA_BOLETA_IDPER] FOREIGN KEY ([IDPER]) REFERENCES [dbo].[persona] ([IDPER])
GO
