CREATE TABLE [dbo].[PRODUCTOS]
(
[IDPRO] [int] NOT NULL IDENTITY(1, 1),
[NOMPRO] [varchar] (150) COLLATE Modern_Spanish_CI_AS NULL,
[PREPRO] [float] NULL,
[CANTPRO] [int] NULL,
[IDCAT] [int] NULL,
[ESTPRO] [char] (1) COLLATE Modern_Spanish_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRODUCTOS] ADD CONSTRAINT [PK__PRODUCTO__98FA2D9117A56756] PRIMARY KEY CLUSTERED  ([IDPRO]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRODUCTOS] ADD CONSTRAINT [CATEGORIA_PRODUCTOS_IDCAT] FOREIGN KEY ([IDCAT]) REFERENCES [dbo].[CATEGORIA] ([IDCAT])
GO
